### ISSUE TITLE
Authenticate Request fails after successful login

### ISSUE THREAD

**Issue by jagadeshbabut** [divio/django-simple-sso#33]
I am trying to set up an authentication system using `django-simple-sso`. I have followed the `Implementation` steps mentioned in the readme file. Additionally, I have created a login page for authentication at the django-simple-sso Server.

## Environment:
```
Python - 3.5.3
Database - sqlite
OSX - 10.13.4
```
## Installed Packages:
```
Django==2.0.5
django-simple-sso==0.13.2
```

### urls.py:
```
from django.contrib import admin
from django.urls import path, include
from simple_sso.sso_server.server import Server

sso_server = Server()

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
    path('server/', include(sso_server.get_urls())),
]
```

### settings.py:
```
INSTALLED_APPS = [
    ...
    'simple_sso.sso_server',
]
```

### app/urls.py:
```
from django.urls import path
from app import views

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]
```

### app/views.py:
```
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth import login, logout
from app.forms import LoginForm

def login_view(request):
    if request.user.is_authenticated:
        next = request.GET.get('next')
        return HttpResponseRedirect(next)
    else:
        form = LoginForm(request.POST or None)
        if request.POST and form.is_valid():
            user = form.login(request)
            if user:
                login(request, user)
                next = request.GET.get('next')
                return HttpResponseRedirect(next)
        return render(request, 'login.html', {'login_form': form})


def logout_view(request):
    if request.user.is_authenticated:
        logout(request)
    return HttpResponseRedirect('/')
```

Client credentials are created as mentioned in the `Implementation` steps.

Server application is run on port `http://localhost:8000`

### urls.py:
```
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from simple_sso.sso_client.client import Client

sso_client = Client(settings.SIMPLE_SSO_SERVER, settings.SIMPLE_SSO_KEY, settings.SIMPLE_SSO_SECRET)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('client/', include(sso_client.get_urls())),
]
```

### settings.py:
```
...
SIMPLE_SSO_SECRET='secret_key'
SIMPLE_SSO_KEY='public_key'
SIMPLE_SSO_SERVER='http://localhost:8000/server/'
```

Client application is run on port `http://localhost:8001`

## Problem Statement:
When I access the client application url `http://localhost:8001/client/`
- Request flows to the server application `http://localhost:8000/server/`
- Redirects to `http://localhost:8000/login//?next=%2Fserver%2Fauthorize%2F%3Ftoken%3Dsometoken` and when I enter the correct username and password, login happens successfully
-  Internally it redirects to`http://localhost:8000/server/authorize/?token=sometoken` and verification request happens `http://localhost:8000/server/verify/` and I receive the following error:
```
Traceback (most recent call last):
  File "/Users/jagadesh/.virtualenvs/sso_testing/lib/python3.5/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/jagadesh/.virtualenvs/sso_testing/lib/python3.5/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/jagadesh/.virtualenvs/sso_testing/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jagadesh/.virtualenvs/sso_testing/lib/python3.5/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/jagadesh/.virtualenvs/sso_testing/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/jagadesh/.virtualenvs/sso_testing/lib/python3.5/site-packages/simple_sso/sso_client/client.py", line 59, in get
    user = self.client.get_user(access_token)
  File "/Users/jagadesh/.virtualenvs/sso_testing/lib/python3.5/site-packages/simple_sso/sso_client/client.py", line 110, in get_user
    user_data = self.consumer.consume(url, data)
  File "/Users/jagadesh/.virtualenvs/sso_testing/lib/python3.5/site-packages/webservices/models.py", line 55, in consume
    body = self.send_request(url, data=signed_data, headers=headers)
  File "/Users/jagadesh/.virtualenvs/sso_testing/lib/python3.5/site-packages/webservices/sync.py", line 13, in send_request
    self.raise_for_status(response.status_code, response.content)
  File "/Users/jagadesh/.virtualenvs/sso_testing/lib/python3.5/site-packages/webservices/models.py", line 67, in raise_for_status
    raise BadRequest(message)
webservices.exceptions.BadRequest: b'Failed to process the request'
[03/May/2018 14:57:59] "GET /client/authenticate/?access_token=IlIzVkcxcjNuak1uRjIxUDE3V0JCTkp2cVdXbGFoNkJidmxqczYwZ3Qycmx0TnF3Q3ZUMmZHcjJ2NWFRV3BscVQi.Dcy09w.ga7zSLKJ4jnbsHUGEaVUB-5m6IM&next=%2F HTTP/1.1" 500 91586
```

P.S: The Implementation steps along with an example would have been more helpful.

**Comment by paulwinex** [comment]
Hi Jagadesh! Did you fix your problem? I have the same error after I replaced the standard user with custom EmailUser.

**Comment by jagadeshbabut** [comment]
@paulwinex I couldn't spend time triaging this issue. But, I have created my own `sso-idp` & `sso-sp` applications and used it for a closed source project.

**Comment by nijel** [comment]
I got this error when server User model is different than what app expects. Unfortunately there is no error logging implemented, so it's hard to figure out.

The following code crashed (because my User model didn't have one of used fields):

https://github.com/aldryn/django-simple-sso/blob/430cd87b8978026947423f290eb189bfd76b9e01/simple_sso/sso_server/server.py#L155-L168
